version: "3.9"

services:
  server:
    build: .
    init: true
    # restart: always
    volumes:
      - .:/usr/src/app/server
    ports:
      - 5000:5000
    tty: true
    links:
      - mysql
    depends_on:
      - mysql

  client:
    build: .
    init: true
    # restart: always
    volumes:
      - .:/usr/src/app/client
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - server
    links:
      - server

  mysql:
    image: mysql
    # restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "hmsv2"
      MYSQL_USER: "rashid"
      MYSQL_PASSWORD: "rashid123"
      MYSQL_ROOT_PASSWORD: "rashid123"

volumes:
  db:
